baseURL = 'https://blog.24toumy.top'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
title = "Toumy24's Blog"
theme = "reimu"

[languages]
  [languages.zh-CN]
    languageName = '简体中文'
    weight = 1
    hasCJKLanguage = true

[outputs]
  home = ["HTML", "RSS"]

[markup.highlight]
  guessSyntax = true
  noClasses = false