baseURL = 'https://blog.24toumy.top'
title = "Toumy24's Blog"
theme = "reimu"
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'

[languages]
  [languages.zh-CN]
    languageName = '简体中文'
    weight = 1
    hasCJKLanguage = true

[markup.highlight]
guessSyntax = true
noClasses = false